

all: Main.c Serial.c CircFifo.c Timers.c savetobmp.c thirdstream.c
	@echo "############################################"
	@echo "###  COMPILING BINARIES                  ###"
	@echo "############################################"
	@echo 	
	gcc *.c -o test.o -lrt
	
